var annotated_dup =
[
    [ "Alarmable", "class_alarmable.html", "class_alarmable" ],
    [ "AlarmableManager", "class_alarmable_manager.html", "class_alarmable_manager" ],
    [ "CameraManager", "class_camera_manager.html", "class_camera_manager" ],
    [ "Collidable", "class_collidable.html", "class_collidable" ],
    [ "Drawable", "class_drawable.html", "class_drawable" ],
    [ "Drawable2D", "class_drawable2_d.html", "class_drawable2_d" ],
    [ "FontManager", "class_font_manager.html", "class_font_manager" ],
    [ "FreeCam", "class_free_cam.html", null ],
    [ "FreezeTime", "class_freeze_time.html", null ],
    [ "Game", "class_game.html", "class_game" ],
    [ "GameObject", "class_game_object.html", "class_game_object" ],
    [ "ImageManager", "class_image_manager.html", "class_image_manager" ],
    [ "Inputable", "class_inputable.html", "class_inputable" ],
    [ "MathTools", "class_math_tools.html", "class_math_tools" ],
    [ "ModelManager", "class_model_manager.html", "class_model_manager" ],
    [ "Panel", "class_panel.html", "class_panel" ],
    [ "Scene", "class_scene.html", "class_scene" ],
    [ "SceneManager", "class_scene_manager.html", "class_scene_manager" ],
    [ "ScreenLog", "class_screen_log.html", "class_screen_log" ],
    [ "ShaderManager", "class_shader_manager.html", "class_shader_manager" ],
    [ "Sprite", "class_sprite.html", "class_sprite" ],
    [ "SpriteString", "class_sprite_string.html", "class_sprite_string" ],
    [ "TextureManager", "class_texture_manager.html", "class_texture_manager" ],
    [ "TimeManager", "class_time_manager.html", "class_time_manager" ],
    [ "Updatable", "class_updatable.html", "class_updatable" ],
    [ "Visualizer", "class_visualizer.html", "class_visualizer" ]
];